#!/usr/bin/env python3
"""Generate compact browser data for exact native dialogue predicates."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EVIDENCE = (
    ROOT / "tools" / "evidence" / "dialogue-predicate-values.json"
)
DEFAULT_OUTPUT = (
    ROOT / "play" / "data" / "dialogue"
    / "nativePredicateValues.generated.js"
)


def build_runtime_data(evidence: dict[str, Any]) -> dict[str, Any]:
    if evidence.get("schema") != (
        "new-yokosuka-dialogue-predicate-values-v6"
    ):
        raise ValueError("predicate evidence schema is not supported")
    table = evidence["nativeSpatialTable"]
    if table["recordCount"] != 13 or len(table["records"]) != 13:
        raise ValueError("native spatial table is incomplete")
    runtime_value = next(
        item
        for item in evidence["nativeValueTypes"]
        if item["encodedGroup"] == "0xa0"
    )
    actor_runtime = evidence["nativeActorRuntimeValues"]
    return {
        "schema": "new-yokosuka-native-dialogue-predicate-data-v2",
        "generatedFrom": {
            "schema": evidence["schema"],
            "executableSha256": evidence[
                "executableEvidence"
            ]["sha256"],
            "spatialTableSha256": table["sha256"],
        },
        "runtimeComponentModes": runtime_value["modes"],
        "calendar": evidence["nativeCalendar"],
        "currency": evidence["nativeCurrency"],
        "stateBanks": evidence["nativeStateBanks"],
        "actorRuntimeValues": {
            key: actor_runtime[key]
            for key in (
                "identityTableAddress",
                "identityTableCount",
                "zeroIdentityRule",
                "nonzeroIdentityRule",
                "runtimeFieldOffset",
                "runtimeFieldQuery",
                "runtimeFieldProducer",
                "numericMeaningPolicy",
            )
        },
        "spatialTable": {
            "comparison": table["comparison"],
            "boundaryRule": table["boundaryRule"],
            "records": table["records"],
        },
        "operators": evidence["nativeOperators"],
    }


def write_module(path: Path, data: dict[str, Any]) -> None:
    encoded = json.dumps(data, indent=2, ensure_ascii=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by tools/scripting/generate_native_dialogue_predicate_data.py.\n"
        "// Do not hand-edit; regenerate from verified predicate evidence.\n"
        "export const NATIVE_DIALOGUE_PREDICATE_DATA = "
        f"Object.freeze({encoded});\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--evidence",
        type=Path,
        default=DEFAULT_EVIDENCE,
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    data = build_runtime_data(json.loads(args.evidence.read_text()))
    write_module(args.output, data)
    print(
        f"Wrote {args.output}: "
        f"{len(data['spatialTable']['records'])} spatial records"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
