#!/usr/bin/env python3
"""Generate browser data for exact native actor progress-state indices."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EVIDENCE = (
    ROOT / "tools" / "evidence" / "dialogue-progress-state.json"
)
DEFAULT_OUTPUT = (
    ROOT / "play" / "data" / "dialogue"
    / "nativeProgressIndices.generated.js"
)


def build_runtime_data(evidence: dict[str, Any]) -> dict[str, Any]:
    if evidence.get("schema") != "new-yokosuka-dialogue-progress-state-v1":
        raise ValueError("dialogue progress evidence schema is not supported")
    table = evidence["nativeIdentityIndex"]
    entries = table["entries"]
    if table["fixedIndexCount"] != 301 or len(entries) != 301:
        raise ValueError("native fixed progress-index table is incomplete")
    if table["dynamicIndexStart"] != 301 or table["dynamicIndexCount"] != 24:
        raise ValueError("native dynamic progress-index pool is not exact")

    identities: list[str | None] = [None] * 301
    by_identity: dict[str, int] = {}
    for expected_index, entry in enumerate(entries):
        index = entry["index"]
        identity = entry["identity"]
        if index != expected_index:
            raise ValueError("native progress identities are not index ordered")
        if identity is not None:
            if not isinstance(identity, str) or len(identity) != 4:
                raise ValueError(
                    f"invalid native progress identity at index {index}"
                )
            if identity in by_identity:
                raise ValueError(
                    f"duplicate native progress identity {identity}"
                )
            by_identity[identity] = index
        identities[index] = identity

    if len(by_identity) != table["namedIdentityCount"]:
        raise ValueError("native named progress identity count does not match")
    return {
        "schema": "new-yokosuka-native-dialogue-progress-index-v1",
        "generatedFrom": {
            "schema": evidence["schema"],
            "executableSha256": evidence["executableEvidence"]["sha256"],
            "runtimeAddress": table["runtimeAddress"],
        },
        "fixedIdentities": identities,
        "indexByIdentity": by_identity,
        "dynamicIndexStart": table["dynamicIndexStart"],
        "dynamicIndexCount": table["dynamicIndexCount"],
    }


def write_module(path: Path, data: dict[str, Any]) -> None:
    encoded = json.dumps(data, indent=2, ensure_ascii=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by "
        "tools/scripting/generate_native_dialogue_progress_index_data.py.\n"
        "// Do not hand-edit; regenerate from verified progress evidence.\n"
        "export const NATIVE_DIALOGUE_PROGRESS_INDEX_DATA = "
        f"Object.freeze({encoded});\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--evidence",
        type=Path,
        default=DEFAULT_EVIDENCE,
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    data = build_runtime_data(json.loads(args.evidence.read_text()))
    write_module(args.output, data)
    print(
        f"Wrote {args.output}: "
        f"{len(data['indexByIdentity'])} fixed actor identities"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
