#!/usr/bin/env python3
"""Join native actor dialogue resources to their exact progress records."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from tools.scripting.generate_native_dialogue_selector_data import (
    DEFAULT_DIALOGUE_INVENTORY,
    DEFAULT_HUMANS,
    DEFAULT_SCHEDULED_ACTORS,
    extract_selector_data,
    scheduled_actor_labels,
)


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PROGRESS_EVIDENCE = (
    ROOT / "tools" / "evidence" / "dialogue-progress-state.json"
)
DEFAULT_OUTPUT = (
    ROOT / "play" / "data" / "dialogue"
    / "nativeActorRuntime.generated.js"
)


def build_runtime_data(
    selectors: dict[str, Any],
    progress_evidence: dict[str, Any],
) -> dict[str, Any]:
    if selectors.get("schema") != "new-yokosuka-native-dialogue-selectors-v1":
        raise ValueError("native selector schema is not supported")
    if progress_evidence.get("schema") != (
        "new-yokosuka-dialogue-progress-state-v1"
    ):
        raise ValueError("native progress evidence schema is not supported")

    progress = progress_evidence["nativeIdentityIndex"]
    fixed_indices = {
        entry["identity"]: entry["index"]
        for entry in progress["entries"]
        if entry["identity"] is not None
    }
    bindings = {}
    fixed_count = 0
    dynamic_count = 0
    for actor_code, message_resource in sorted(
        selectors["messageResources"].items()
    ):
        identity = message_resource["authoredPersonIdentity"]
        fixed_index = fixed_indices.get(identity)
        allocation = "fixed" if fixed_index is not None else "dynamic"
        if fixed_index is None:
            dynamic_count += 1
        else:
            fixed_count += 1
        bindings[actor_code] = {
            "actorCode": actor_code,
            "actorLabel": message_resource["actorLabel"],
            "authoredPersonIdentity": identity,
            "participantFourccs": message_resource["participantFourccs"],
            "participantFacingTargets": message_resource[
                "participantFacingTargets"
            ],
            "messageCount": len(message_resource["messages"]),
            "voicePath": message_resource["voicePath"],
            "progressAllocation": allocation,
            "fixedProgressIndex": fixed_index,
        }

    if len(bindings) != selectors["resourceCount"]:
        raise ValueError("actor runtime binding count does not match selectors")
    return {
        "schema": "new-yokosuka-native-dialogue-actor-runtime-v1",
        "generatedFrom": {
            "humansArchiveSha256": selectors["generatedFrom"]["sha256"],
            "executableSha256": progress_evidence[
                "executableEvidence"
            ]["sha256"],
            "progressIdentityTableAddress": progress["runtimeAddress"],
        },
        "resourceCount": len(bindings),
        "fixedProgressBindingCount": fixed_count,
        "dynamicProgressBindingCount": dynamic_count,
        "resources": bindings,
    }


def write_module(path: Path, data: dict[str, Any]) -> None:
    encoded = json.dumps(
        data,
        ensure_ascii=True,
        separators=(",", ":"),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by tools/scripting/generate_native_dialogue_actor_runtime_data.py.\n"
        "// Exact HUMANS.AFS actor resources joined to executable progress "
        "indices.\n"
        "export const NATIVE_DIALOGUE_ACTOR_RUNTIME = "
        f"Object.freeze({encoded});\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--humans", type=Path, default=DEFAULT_HUMANS)
    parser.add_argument(
        "--scheduled-actors",
        type=Path,
        default=DEFAULT_SCHEDULED_ACTORS,
    )
    parser.add_argument(
        "--dialogue-inventory",
        type=Path,
        default=DEFAULT_DIALOGUE_INVENTORY,
    )
    parser.add_argument(
        "--progress-evidence",
        type=Path,
        default=DEFAULT_PROGRESS_EVIDENCE,
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    inventory = (
        json.loads(args.dialogue_inventory.read_text(encoding="utf-8"))
        if args.dialogue_inventory.is_file()
        else None
    )
    selectors = extract_selector_data(
        args.humans.read_bytes(),
        scheduled_actor_labels(args.scheduled_actors),
        inventory,
    )
    data = build_runtime_data(
        selectors,
        json.loads(args.progress_evidence.read_text(encoding="utf-8")),
    )
    write_module(args.output, data)
    print(
        f"Wrote {args.output}: {data['resourceCount']} actor resources "
        f"({data['fixedProgressBindingCount']} fixed, "
        f"{data['dynamicProgressBindingCount']} dynamic)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
