#!/usr/bin/env python3
"""Bind proven JOMO shared-object callbacks to engine transform selectors.

This intentionally emits only the selector-11 JOMO path whose native
operation-0x0139 dataflow is closed. Other callback families remain absent
rather than being guessed from model names or table proximity.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any


JOMO_CALLBACK_SELECTOR = 11
ENGINE_SELECTOR_DELTA = -1


def engine_family(
    evidence: dict[str, Any],
    selector: int,
) -> dict[str, Any]:
    for family in evidence["families"]:
        if selector in family["selectors"]:
            return family
    raise RuntimeError(f"No engine family contains selector {selector}")


def write_browser_module(path: Path, result: dict[str, Any]) -> None:
    bindings = {
        entry["objectTag"]: {
            "groupIndex": entry["groupIndex"],
            "engineSelector": entry["engineSelector"],
            "transformChannel": entry["transformChannel"],
            # This is an SCN3 action-dispatch slot. It is not necessarily the
            # MT5 render-node flag, even though the values coincide for some
            # object families.
            "actionRouteNodeOrVariant": entry["route"]["nodeOrVariant"],
            "actionId": entry["actionId"],
        }
        for entry in result["objects"]
    }
    pairs: dict[str, dict[str, Any]] = {}
    by_action: dict[tuple[int, int], list[dict[str, Any]]] = defaultdict(list)
    for entry in result["objects"]:
        by_action[(entry["groupIndex"], entry["actionId"])].append(entry)
    for entries in by_action.values():
        if len(entries) != 2:
            continue
        left, right = entries
        pair_id = left["objectTag"][:-1]
        for current, partner in ((left, right), (right, left)):
            pairs[current["objectTag"]] = {
                "pairId": pair_id,
                "partnerTag": partner["objectTag"],
                "actionRouteNodeOrVariant": (
                    current["route"]["nodeOrVariant"]
                ),
                "engineSelector": current["engineSelector"],
                "transformChannel": current["transformChannel"],
            }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by tools/worlds/extract_jomo_object_action_bindings.py.\n"
        "// Do not classify additional objects here without extending the "
        "native trace.\n\n"
        "export const JOMO_POSITION_X_BINDINGS = Object.freeze("
        + json.dumps(bindings, indent=2)
        + ");\n\n"
        "export const JOMO_POSITION_X_PAIRS = Object.freeze("
        + json.dumps(pairs, indent=2)
        + ");\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("shared_dispatch", type=Path)
    parser.add_argument("selector_families", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--browser-out", type=Path)
    args = parser.parse_args()

    shared = json.loads(args.shared_dispatch.read_text())
    families = json.loads(args.selector_families.read_text())
    engine_selector = JOMO_CALLBACK_SELECTOR + ENGINE_SELECTOR_DELTA
    family = engine_family(families, engine_selector)

    groups = []
    objects = []
    for group in shared["groups"]:
        callbacks = group.get("callbackTokens", [])
        if not callbacks or callbacks[0].get("selector") != JOMO_CALLBACK_SELECTOR:
            continue
        if callbacks[0].get("opcode") != "0x05a9":
            continue

        group_binding = {
            "groupIndex": group["index"],
            "groupFileOffset": group["fileOffset"],
            "jomoCallbackSelector": JOMO_CALLBACK_SELECTOR,
            "jomoCallbackFunctionFileOffset": callbacks[0].get(
                "functionFileOffset"
            ),
            "engineSelectorExpression": (
                f"{JOMO_CALLBACK_SELECTOR} - 1"
            ),
            "engineSelector": engine_selector,
            "transformChannel": family["transformChannel"],
            "nodeOffset": family["nodeOffset"],
            "objectTags": group["objectTags"],
        }
        groups.append(group_binding)

        for tag in group["objectTags"]:
            record = group.get("records", {}).get(tag)
            entry = {
                "objectTag": tag,
                "groupIndex": group["index"],
                "engineSelector": engine_selector,
                "transformChannel": family["transformChannel"],
                "nodeOffset": family["nodeOffset"],
            }
            if record is not None:
                entry["recordFileOffset"] = record["fileOffset"]
                entry["actionId"] = record["actionId"]
                entry["route"] = record["route"]
            objects.append(entry)

    result = {
        "schema": "new-yokosuka-jomo-object-action-bindings-v1",
        "source": {
            "sharedDispatch": str(args.shared_dispatch),
            "selectorFamilies": str(args.selector_families),
        },
        "method": {
            "runtimeInputRequired": False,
            "emulatorClicksRequired": False,
            "jomoCallbackSelector": JOMO_CALLBACK_SELECTOR,
            "jomoCallbackRuntimeAddress": "0x0c3d7690",
            "jomoCoroutineRuntimeAddress": "0x0c44673c",
            "selectorArithmetic": {
                "loadInstruction": "0x0c446e6c",
                "subtractInstruction": "0x0c446e72",
                "storeInstruction": "0x0c446e74",
                "operation0139Call": "0x0c446ea6",
                "expression": "engineSelector = selectedCallbackSelector - 1",
            },
            "runtimeValidation": {
                "objectTag": "GGB1",
                "selectedCallbackSelector": 11,
                "engineSelector": 10,
            },
            "evidenceBoundary": (
                "Only groups whose primary SCN3 callback is selector 11 are "
                "bound. Other callback families require their own native "
                "dataflow trace."
            ),
        },
        "summary": {
            "boundGroupCount": len(groups),
            "boundObjectCount": len(objects),
            "engineSelector": engine_selector,
            "transformChannel": family["transformChannel"],
        },
        "groups": groups,
        "objects": objects,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2) + "\n")
    if args.browser_out is not None:
        write_browser_module(args.browser_out, result)
    print(
        f"Wrote {args.out} "
        f"({len(groups)} groups, {len(objects)} objects)"
    )


if __name__ == "__main__":
    main()
