#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import { WORLDS } from "../../play/config/worlds.js";

const paths = {
  mapsCsv: "public/data/maps.csv",
  transitionCatalog: "tools/evidence/map-transition-catalog.json",
  portalInventory: "tools/evidence/player-portal-inventory.json",
  scheduleCatalog: "play/data/shenmue1-schedule-catalog.json",
  worldsConfig: "play/config/worlds.js",
  nativeMapTransitions: "play/data/native-map-transitions.json",
  shenmue2BoundaryTransitions: "play/data/shenmue2-boundary-transitions.json",
};
const outputPath = "docs/reference/areas-and-worlds.generated.md";
const check = process.argv.includes("--check");
const read = (path) => fs.readFileSync(path, "utf8");
const hash = (text) => crypto.createHash("sha256").update(text).digest("hex");
const sourceTexts = Object.fromEntries(Object.entries(paths).map(([key, path]) => [key, read(path)]));
const transitions = JSON.parse(sourceTexts.transitionCatalog);
const portals = JSON.parse(sourceTexts.portalInventory);
const schedules = JSON.parse(sourceTexts.scheduleCatalog);
const records = new Map();

function recordFor(area) {
  if (!records.has(area)) {
    records.set(area, {
      area,
      csvNames: new Set(),
      csvLocations: new Set(),
      mapSources: [],
      incoming: 0,
      outgoing: 0,
      portalsIn: 0,
      portalsOut: 0,
      schedulePrograms: new Set(),
      worlds: [],
    });
  }
  return records.get(area);
}

for (const line of sourceTexts.mapsCsv.split(/\r?\n/).slice(1)) {
  if (!line.trim()) continue;
  const [rawName, rawId, rawLocation] = line.split(";").map((part) => part.trim());
  if (!/^[A-Z0-9]{4}$/.test(rawId)) continue;
  const record = recordFor(rawId);
  if (rawName) record.csvNames.add(rawName);
  if (rawLocation) record.csvLocations.add(rawLocation);
}
for (const map of transitions.maps) {
  recordFor(map.source.area).mapSources.push(map);
}
for (const edge of transitions.exactEdges) {
  recordFor(edge.source.area).outgoing += 1;
  recordFor(edge.destination.area).incoming += 1;
}
for (const portal of portals.portals) {
  recordFor(portal.source.area).portalsOut += 1;
  recordFor(portal.destination.area).portalsIn += 1;
}
for (const program of schedules.programs) {
  for (const area of program.selectedAreas || []) {
    recordFor(area).schedulePrograms.add(program.programId);
  }
}
for (const world of Object.values(WORLDS)) {
  if (!/^[A-Z0-9]{4}$/.test(world.nativeArea || "")) continue;
  recordFor(world.nativeArea).worlds.push({
    id: world.id,
    label: world.label,
    type: world.interior ? "interior" : "exterior",
  });
}

const list = (values, code = false) => {
  const sorted = [...new Set(values)].sort();
  if (!sorted.length) return "—";
  return sorted.map((value) => code ? `\`${value}\`` : value).join("; ");
};
const rows = [];
let namedCount = 0;
let unresolvedCount = 0;
for (const record of [...records.values()].sort((a, b) => a.area.localeCompare(b.area))) {
  const browserLabels = record.worlds.map(({ label }) => label).filter(Boolean);
  const names = [...new Set([...browserLabels, ...record.csvNames])];
  const label = names.length ? list(names) : "unresolved";
  if (names.length) namedCount += 1;
  else unresolvedCount += 1;
  const worldIds = record.worlds.map(({ id }) => id);
  const worldTypes = record.worlds.map(({ type }) => type);
  const evidence = [
    record.mapSources.length ? `MAPINFO ${record.mapSources.length}` : null,
    record.csvNames.size ? "maps.csv" : null,
    record.schedulePrograms.size ? `schedule ${record.schedulePrograms.size}` : null,
    record.worlds.length ? "worlds.js" : null,
  ].filter(Boolean);
  const confidence = names.length ? "confirmed" : "unresolved";
  rows.push(`| \`${record.area}\` | ${label} | ${list(record.csvLocations)} | ${list(worldIds, true)} | ${list(worldTypes)} | ${record.mapSources.length} | ${record.outgoing} / ${record.incoming} | ${record.portalsOut} / ${record.portalsIn} | ${record.schedulePrograms.size} | ${evidence.join("; ") || "transition endpoint only"} | \`${confidence}\` |`);
}

const generated = `# Complete generated area and world index

<!-- Generated by node tools/reference/generate_identifier_area_reference.mjs. Do not edit manually. -->

This is the exhaustive union of four-character areas in the current Shenmue I
MAPINFO transition extraction, exact transition destinations, map CSV, schedule
catalog, and configured browser worlds. It contains ${records.size} codes:
${namedCount} with an evidence-backed display label and ${unresolvedCount}
remaining \`unresolved\`. Browser-only Shenmue II worlds are included because
they are current project destinations; their presence does not make them part
of the Shenmue I MAPINFO corpus.

Input SHA-256:

${Object.entries(paths).map(([key, path]) => `- \`${path}\`: \`${hash(sourceTexts[key])}\``).join("\n")}

Regenerate with \`node tools/reference/generate_identifier_area_reference.mjs\`; add
\`--check\` to validate freshness. Transition counts are exact operation-0x0030
edges. Portal counts include only the inventory's validated native player
portals. A transition endpoint alone does not prove a physical portal.

“Location group” is the CSV's broad grouping, not a native parent-child
relationship. Multiple display labels are preserved rather than silently
choosing between duplicates. Browser type applies only to configured worlds;
a dash does not prove an area is exterior. \`confirmed\` in the label column
means the text is exact to the cited map catalog or current browser
configuration; it does not promote a project-facing browser label into an
original native location name.

| Native area | Evidence-backed display label(s) | Location group(s) | Browser world ID(s) | Browser type(s) | MAPINFO variants | Exact edges out / in | Portals out / in | Schedule programs | Evidence membership | Confidence |
| --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- |
${rows.join("\n")}
`;

if (check) {
  if (!fs.existsSync(outputPath) || read(outputPath) !== generated) {
    console.error(`${outputPath} is stale; run node tools/reference/generate_identifier_area_reference.mjs`);
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, generated);
  console.log(`Wrote ${outputPath} (${records.size} area codes)`);
}
