#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";

const scheduledPath = "tools/evidence/scheduled-actor-operation-coverage.json";
const nativePath = "tools/evidence/native-operation-semantics.json";
const scheduledOutput = "docs/reference/scheduled-actor-operations.generated.md";
const nativeOutput = "docs/reference/native-operations.generated.md";
const check = process.argv.includes("--check");
const read = (path) => fs.readFileSync(path, "utf8");
const hash = (text) => crypto.createHash("sha256").update(text).digest("hex");
const escapeCell = (value) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
const scheduledText = read(scheduledPath);
const nativeText = read(nativePath);
const scheduled = JSON.parse(scheduledText);
const native = JSON.parse(nativeText);

const scheduledRows = [...scheduled.operationFamilies]
  .sort((a, b) => a.operation - b.operation)
  .map((family) => `| \`${family.operationHex}\` | ${family.occurrenceCount} | ${family.actorCodeCount} | ${escapeCell(family.nativeClass)} | \`${family.browserStatus}\` | ${escapeCell(family.browserEffect)} |`);
const scheduledGenerated = `# Complete generated scheduled-actor operation index

<!-- Generated by node tools/reference/generate_identifier_operation_references.mjs. Do not edit manually. -->

This index contains all ${scheduled.operationFamilies.length} operation families
present in the current scheduled-actor runtime projection (${scheduled.summary.operationOccurrenceCount}
occurrences). Status describes reconstruction coverage, not narrative meaning.
“Exact no-visible-effect” means the proven scheduler-side behavior has no
visible browser effect; it does not mean arbitrary surrounding engine systems
could never observe the operation.

Source: \`${scheduledPath}\` (SHA-256 \`${hash(scheduledText)}\`). Regenerate
with \`node tools/reference/generate_identifier_operation_references.mjs\`; add
\`--check\` to validate freshness.

| Operation | Occurrences | Actor codes | Native class | Reconstruction status | Bounded behavior |
| --- | ---: | ---: | --- | --- | --- |
${scheduledRows.join("\n")}
`;

const nativeRows = [...native.operations]
  .sort((a, b) => a.operationId - b.operationId)
  .map((operation) => {
    const constraints = (operation.argumentConstraints || []).map((constraint) => (
      `arg ${constraint.index}: ${(
        constraint.values || constraint.kinds || []
      ).map((value) => `\`${value}\``).join(", ")}`
    )).join("; ") || "—";
    const sources = operation.sources.map((source) => `\`${source}\``).join("; ");
    return `| \`${operation.operationHex}\` | \`${operation.semanticId}\` | \`${operation.handlerAddress}\` | ${constraints} | ${escapeCell(operation.provenBehavior)} | ${sources} | \`confirmed\` |`;
  });
const nativeGenerated = `# Complete generated proven native-operation index

<!-- Generated by node tools/reference/generate_identifier_operation_references.mjs. Do not edit manually. -->

This index contains every operation in the current reviewed semantic registry:
${native.operations.length} evidence-backed operations. It is comprehensive for
that registry, not for the engine's entire dispatcher. Missing operations and
unconstrained modes remain numeric and unresolved.

Source: \`${nativePath}\` (SHA-256 \`${hash(nativeText)}\`). Regenerate with
\`node tools/reference/generate_identifier_operation_references.mjs\`; add \`--check\`
to validate freshness.

| Operation | Semantic ID | Handler | Proven argument constraints | Proven behavior | Evidence | Confidence |
| --- | --- | --- | --- | --- | --- | --- |
${nativeRows.join("\n")}
`;

for (const [path, content] of [[scheduledOutput, scheduledGenerated], [nativeOutput, nativeGenerated]]) {
  if (check) {
    if (!fs.existsSync(path) || read(path) !== content) {
      console.error(`${path} is stale; run node tools/reference/generate_identifier_operation_references.mjs`);
      process.exitCode = 1;
    }
  } else {
    fs.writeFileSync(path, content);
    console.log(`Wrote ${path}`);
  }
}
