#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";

const paths = {
  predicateValues: "tools/evidence/dialogue-predicate-values.json",
  worldState: "tools/evidence/scripted-world-state-inventory.json",
  researchedFlags: "docs/reference/researched-flags.json",
};
const outputPath = "docs/reference/state-banks-and-flags.generated.md";
const check = process.argv.includes("--check");
const read = (path) => fs.readFileSync(path, "utf8");
const hash = (text) => crypto.createHash("sha256").update(text).digest("hex");
const texts = Object.fromEntries(Object.entries(paths).map(([key, path]) => [key, read(path)]));
const predicates = JSON.parse(texts.predicateValues);
const worldState = JSON.parse(texts.worldState);
const researched = JSON.parse(texts.researchedFlags);
const confidenceVocabulary = new Set(["confirmed", "high", "medium", "low", "unresolved"]);
const aliases = new Map();

for (const entry of researched.entries) {
  const key = `${entry.bank}:${entry.index}`;
  const bank = predicates.nativeStateBanks.banks.find(({ bank: value }) => value === entry.bank);
  if (!bank || entry.index < 0 || entry.index >= bank.capacity) throw new Error(`Flag ${key} is outside its native bank`);
  if (aliases.has(key)) throw new Error(`Duplicate researched flag ${key}`);
  if (!confidenceVocabulary.has(entry.confidence)) throw new Error(`Invalid confidence for ${key}`);
  for (const evidencePath of entry.evidence) {
    if (!fs.existsSync(evidencePath)) throw new Error(`Missing evidence ${evidencePath} for ${key}`);
  }
  aliases.set(key, entry);
}

const usage = new Map();
for (const map of worldState.maps) {
  for (const group of map.operationGroups) {
    if (group.kind !== "persistent-flag" || !Number.isInteger(group.flagOrIndex)) continue;
    const key = `${group.namespace}:${group.flagOrIndex}`;
    if (!usage.has(key)) usage.set(key, { reads: 0, writes: 0, areas: new Set() });
    const item = usage.get(key);
    item[group.action === "read" ? "reads" : "writes"] += group.callFileOffsets?.length || 0;
    item.areas.add(`${map.area}/scene-${map.scene}`);
  }
}

const rows = [];
let observedCount = 0;
for (const bank of [...predicates.nativeStateBanks.banks].sort((a, b) => a.bank - b.bank)) {
  for (let index = 0; index < bank.capacity; index += 1) {
    const key = `${bank.bank}:${index}`;
    const item = usage.get(key);
    const alias = aliases.get(key);
    if (item) observedCount += 1;
    const areas = item ? [...item.areas].sort() : [];
    rows.push(`| ${bank.bank} | ${index} | ${alias ? `\`${alias.alias}\`` : "unresolved"} | ${bank.storage} | ${item?.reads || 0} | ${item?.writes || 0} | ${areas.length ? areas.map((area) => `\`${area}\``).join(", ") : "—"} | ${alias?.meaning || "unresolved"} | ${alias?.setter || "unresolved"} | \`${alias?.confidence || "unresolved"}\` |`);
  }
}

const totalCapacity = predicates.nativeStateBanks.banks.reduce((sum, bank) => sum + bank.capacity, 0);
const generated = `# Complete generated persistent-state index

<!-- Generated by node tools/reference/generate_identifier_state_reference.mjs. Do not edit manually. -->

This index contains every addressable entry in native persistent banks 2, 3,
and 4: ${totalCapacity} entries total. ${observedCount} have an exact literal
read or write in the current all-map scripted-world inventory. Zero calls means
“not statically observed in that inventory,” not “unused.” Runtime-valued
indexes remain counted only in the inventory summary and are never assigned to
a guessed row.

Input SHA-256:

${Object.entries(paths).map(([key, path]) => `- \`${path}\`: \`${hash(texts[key])}\``).join("\n")}

Regenerate with \`node tools/reference/generate_identifier_state_reference.mjs\`; add
\`--check\` to validate freshness. Aliases come only from
\`${paths.researchedFlags}\` and remain project research labels. The numeric
bank and index are authoritative.

| Bank | Index | Research alias | Storage | Literal reads | Literal writes | Map/scene consumers | Current meaning | Exact setter | Confidence |
| ---: | ---: | --- | --- | ---: | ---: | --- | --- | --- | --- |
${rows.join("\n")}
`;

if (check) {
  if (!fs.existsSync(outputPath) || read(outputPath) !== generated) {
    console.error(`${outputPath} is stale; run node tools/reference/generate_identifier_state_reference.mjs`);
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, generated);
  console.log(`Wrote ${outputPath} (${totalCapacity} bank entries)`);
}
