#!/usr/bin/env node
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MotnLoader } from "../../src/MotnLoader.js";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const sourceCandidates = [
  process.env.SHENMUE_DISC3_EXTRACTED_ROOT,
  path.join(repoRoot, "extracted_disc3_v2"),
].filter(Boolean);
const sourceRoot = sourceCandidates.find(existsSync);
if (!sourceRoot) {
  throw new Error(
    `Disc 3 extraction not found. Tried: ${sourceCandidates.join(", ")}`,
  );
}

const sources = Object.freeze({
  global: path.join(sourceRoot, "data/MOTION/MOTION.BIN"),
  battle: path.join(sourceRoot, "data/SCENE/03/MFBT/M_FGT1.BIN"),
});
const soundBankPath = path.join(
  sourceRoot,
  "data/SCENE/03/SOUND/BATTLE_1.SND",
);
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const soundBank = readFileSync(soundBankPath);
const sequenceOffset = soundBank.readUInt32LE(0x2c);
const groupCount = soundBank.readUInt32LE(sequenceOffset) + 1;
const groupDescriptors = Array.from(
  { length: groupCount },
  (_, index) => soundBank.readUInt32LE(
    sequenceOffset + 4 + index * 4,
  ) >>> 16,
);
const validCommandPrefixes = new Set(groupDescriptors.map(
  (descriptor) => descriptor.toString(16).padStart(4, "0"),
));
const validCommandHex = new Set();
for (let groupIndex = 0; groupIndex < groupCount; groupIndex += 1) {
  const descriptorWord = soundBank.readUInt32LE(
    sequenceOffset + 4 + groupIndex * 4,
  );
  const groupOffset = descriptorWord & 0xffff;
  const trackCount = soundBank.readUInt32LE(
    sequenceOffset + groupOffset,
  ) + 1;
  for (let track = 0; track < trackCount; track += 1) {
    const trackOffset = soundBank.readUInt32LE(
      sequenceOffset + groupOffset + 4 + track * 4,
    );
    const entryType = soundBank[sequenceOffset + trackOffset + 1];
    if (![0xdc, 0xdd, 0xde, 0xdf].includes(entryType)) continue;
    validCommandHex.add(
      `${
        (descriptorWord >>> 16).toString(16).padStart(4, "0")
      }${track.toString(16).padStart(2, "0")}00`,
    );
  }
}

function cueMap(sourcePath) {
  const bytes = readFileSync(sourcePath);
  const motion = MotnLoader.parse(bytes);
  const sequences = {};
  for (const sequence of motion.sequences) {
    const cues = (sequence.actionMetadata?.soundCues || []).filter(
      ({ commandHex }) => validCommandHex.has(commandHex.toLowerCase()),
    );
    if (cues.length === 0) continue;
    const compact = cues.map(({ frame, commandHex }) => (
      Object.freeze({ frame, commandHex })
    ));
    if (
      sequences[sequence.name]
      && JSON.stringify(sequences[sequence.name]) !== JSON.stringify(compact)
    ) {
      throw new Error(
        `${sourcePath} has conflicting sound metadata for ${sequence.name}`,
      );
    }
    sequences[sequence.name] = Object.freeze(compact);
  }
  return {
    source: path.relative(repoRoot, sourcePath),
    byteLength: bytes.length,
    sha256: sha256(bytes),
    sequences,
  };
}

const banks = Object.fromEntries(Object.entries(sources).map(
  ([bank, sourcePath]) => [bank, cueMap(sourcePath)],
));
const outputPath = path.join(
  repoRoot,
  "play/data/native-combat-sound-cues.js",
);
const generated = `// Generated by tools/audio/build_native_combat_sound_cues.mjs.\n`
  + `// Source-authored MOTION/M_FGT1 frame cues; do not edit by hand.\n`
  + `export const NATIVE_COMBAT_SOUND_CUES = Object.freeze(${
    JSON.stringify({
      schema: "new-yokosuka-native-combat-sound-cues-v1",
      soundBank: {
        source: path.relative(repoRoot, soundBankPath),
        byteLength: soundBank.length,
        sha256: sha256(soundBank),
        validCommandPrefixes: [...validCommandPrefixes],
        playableCommandCount: validCommandHex.size,
      },
      banks,
    }, null, 2)
  });\n`;
writeFileSync(outputPath, generated);
console.log(
  `Wrote ${outputPath}: ${
    Object.values(banks).reduce(
      (sum, bank) => sum + Object.keys(bank.sequences).length,
      0,
    )
  } cue-bearing sequences.`,
);
