#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const [, , inputName, outputName] = process.argv;

if (!inputName || !outputName) {
  console.error(
    "Usage: node tools/actors/build_shenmue_controller_family_data.mjs "
    + "<controller-family-export.json> <output.web.js>",
  );
  process.exit(1);
}

const input = JSON.parse(fs.readFileSync(inputName, "utf8"));
if (!Array.isArray(input.families)) {
  throw new Error(`Unsupported controller-family export: ${inputName}`);
}

function buildFamilies(families) {
  return families.map((family) => {
    const parentByIndex = new Array(family.nodeCount).fill(null);
    for (const node of family.nodes) {
      for (const childIndex of node.childIndices) {
        if (
          !Number.isInteger(childIndex)
          || childIndex < 0
          || childIndex >= family.nodeCount
        ) {
          throw new Error(
            `Family ${family.familyIndex} node ${node.nodeIndex} has invalid `
            + `child ${childIndex}`,
          );
        }
        if (parentByIndex[childIndex] !== null) {
          throw new Error(
            `Family ${family.familyIndex} node ${childIndex} has multiple `
            + "parents",
          );
        }
        parentByIndex[childIndex] = node.nodeIndex;
      }
    }

    return {
      index: family.familyIndex,
      nodeCount: family.nodeCount,
      executableTableEntry: family.entryAddress,
      nodes: family.nodes.map((node) => ({
        index: node.nodeIndex,
        type: node.headerBytes[0],
        solverClass: node.headerBytes[1],
        solverSubtype: node.headerBytes[2],
        descriptorHeader: node.headerBytes,
        parent: parentByIndex[node.nodeIndex],
        children: node.childIndices,
        defaultPosition: node.defaultPosition,
        defaultRotationRaw: node.defaultRotationS16,
      })),
    };
  });
}

let output;
if (input.format === "shenmue-controller-families-v1") {
  const families = buildFamilies(input.families);
  output = {
    format: "shenmue-controller-families-runtime-v1",
    source: {
      program: input.program,
      executableTableAddress: input.tableAddress,
      extractionScript: "tools/ghidra/ExportControllerFamilies.java",
    },
    familyCount: families.length,
    families,
  };
} else if (input.format === "shenmue-controller-families-runtime-v1") {
  output = input;
} else {
  throw new Error(`Unsupported controller-family export: ${inputName}`);
}

if (!outputName.endsWith(".web.js")) {
  throw new Error(
    `Controller-family output must end in .web.js: ${outputName}`,
  );
}

fs.mkdirSync(path.dirname(outputName), { recursive: true });
fs.writeFileSync(
  outputName,
  "// Generated by tools/actors/build_shenmue_controller_family_data.mjs.\n"
  + `export default ${JSON.stringify(output, null, 2)};\n`,
);
